KNN PRACTICE
IDEA Behind it 
- trained data with data points corresponding to their classification 
- use classes of the nearest k data points and choose the majority of the classes where it belongs to predicted classification

ALGORITHM 
1. choose number of k nearest neighbours
2. use distance, take knn data points 
3. count number of data points
4. assign to counted data points with most common




STEP 1 : Choose k nearest neighbour, create most count function

STEP 2: USE DISTANCE to find neighbor : of every point to the new point.which square root of sum of square of distance between two points

STEP 3: Find and 
STEP 4: assign to most commmon

MAKE PREDICTION

In [84]:
import numpy as np

class KNNClassifier:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        predictions = []

        for sample in X_test:
            # Calculate Euclidean distances between the test sample and all training samples
            #axis 1 indicates summation along axis 1
            distances = np.sqrt(np.sum((self.X_train - sample) ** 2, axis=1))

            # Get indices of the k-nearest neighbors
            k_neighbors_indices = np.argsort(distances)[:self.k]

            # Get the corresponding labels of the k-nearest neighbors
            k_neighbors_labels = self.y_train[k_neighbors_indices]

            # Predict the class based on majority vote
            predicted_label = np.argmax(np.bincount(k_neighbors_labels))

            predictions.append(predicted_label)

        return np.array(predictions)

# Example usage:
# Replace X_train, y_train, and X_test with your own data
X_train = np.array([[1, 2], [2, 3], [3, 4], [5, 6]])
y_train = np.array([0, 1, 0, 1])
X_test = np.array([[4, 5], [6,8]])

# Create and train the KNN classifier
knn_classifier = KNNClassifier(k=3)
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
predictions = knn_classifier.predict(X_test)

print("Predictions:", predictions)


Predictions: [1 1]


In [85]:
# Input data - [SAT Score, GPA]
X = [[1590,2.9], [1540,2.7], [1600,2.6], [1590,2.7], [1520,2.5], [1540,2.4], [1560,2.3], [1490,2.3], [1510,2.4],
     [1350,3.9], [1360,3.7], [1370,3.8], [1380,3.7], [1410,3.6], [1420,3.9], [1430,3.4], [1450,3.7], [1460,3.2],
     [1590,3.9], [1540,3.7], [1600,3.6], [1490,3.7], [1520,3.5], [1540,3.4], [1560,3.3], [1460,3.3], [1510,3.4],
     [1340,2.9], [1360,2.4], [1320,2.5], [1380,2.6], [1400,2.1], [1320,2.5], [1310,2.7], [1410,2.1], [1305,2.5],
     [1460,2.7], [1500,2.9], [1300,3.5], [1320,3.6], [1400,2.7], [1300,3.1], [1350,3.1], [1360,2.9], [1305,3.9], 
     [1430,3.0], [1440,2.3], [1440,2.5], [1380,2.1], [1430,2.1], [1400,2.5], [1420,2.3], [1310,2.1], [1350,2.0]]

# Labels - Accepted or Rejected
Y = ['accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted',
     'accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted',
     'accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted','accepted',
     'rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected',
     'rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected',
     'rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected','rejected']

In [86]:
#DATA PROCESSING
X= np.array(X)

def convert_to_binary(labels):
    # Create a binary array where 'accepted' becomes 1 and 'rejected' becomes 0
    binary_labels = np.where(labels == 'accepted', 1, 0)
    return binary_labels

# Convert to binary labels
Y = convert_to_binary(np.array(Y))
Y



array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
#training and testing set size
train_size=int(0.75*np.size(X,0))
test_size=int(0.25*np.size(X,0))
print("Training set size : "+ str(train_size))
print("Testing set size : "+str(test_size))

Training set size : 40
Testing set size : 13


In [88]:
#training set split
X_train=X[0:train_size,:]
X_train =X_train.astype(np.int_)
Y_train=Y[0:train_size]

#testing set split
X_test=X[train_size:,:]
X_test = X_test.astype(np.int_)
Y_test=Y[train_size:]



In [89]:
# Create and train the KNN classifier
knn_classifier = KNNClassifier(k=5)
knn_classifier.fit(X_train, Y_train)

# Make predictions on the test data
predictions = knn_classifier.predict(X_test)
predictions = predictions.astype(np.int_)
predictions

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [90]:
#getting the confusion matrix
tp=len([i for i in range(0,np.size(Y_test,0)) if Y_test[i]==0 and predictions[i]==0])
tn=len([i for i in range(0,np.size(Y_test,0)) if Y_test[i]==0 and predictions[i]==1])
fp=len([i for i in range(0,np.size(Y_test,0)) if Y_test[i]==1 and predictions[i]==0])
fn=len([i for i in range(0,np.size(Y_test,0)) if Y_test[i]==1 and predictions[i]==1])
confusion_matrix=np.array([[tp,tn],[fp,fn]])
print(confusion_matrix)

[[6 8]
 [0 0]]


In [91]:
#Confusion matrix
def confusion_matrix(tp: int, fp: int, fn: int, tn: int) -> float:
    accuracy = (tp + tn ) / (tp + tn+fn +fp)
    precision = (tp) / (tp + fp)
    recall = tp / (tp + fn)
    f1_score = (2*precision*recall) / (precision + recall)
    return accuracy, precision, recall, f1_score


accuracy, precision, recall, f1_score = confusion_matrix(tp, fp, fn, tn)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)



Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


K-Nearest Neighbors (KNN) is a versatile and simple algorithm used for both classification and regression tasks in machine learning. It is a type of instance-based learning, where the model makes predictions based on the similarity of new instances to known instances in the training data. Here's an explanation of how KNN works:

### Basic Steps of KNN:

1. **Input:**
   - The training dataset consists of labeled instances, each having a set of features and a corresponding class label (for classification) or target value (for regression).

2. **Choosing \(k\):**
   - Choose the number of neighbors (\(k\)) to consider when making predictions.
   - A common choice is to use the square root of the total number of instances or other heuristics.

3. **Distance Metric:**
   - Choose a distance metric (e.g., Euclidean distance) to measure the similarity between instances.
   - Euclidean distance is commonly used for numerical features, but other metrics may be suitable for different types of data.

4. **Prediction (Classification):**
   - For a new instance, calculate the distances to all instances in the training set.
   - Identify the \(k\) instances with the shortest distances.
   - Assign the class label that is most frequent among the \(k\) neighbors to the new instance.

5. **Prediction (Regression):**
   - For a new instance, calculate the distances to all instances in the training set.
   - Identify the \(k\) instances with the shortest distances.
   - Predict the target value for the new instance as the average (or weighted average) of the target values of the \(k\) neighbors.

### Key Concepts:

1. **Instance-Based Learning:**
   - KNN is an instance-based learning algorithm as it makes predictions based on instances (data points) in the training set.

2. **Lazy Learning:**
   - KNN is considered a lazy learning algorithm because it doesn't build an explicit model during training. Instead, it memorizes the training instances and uses them for predictions during testing.

3. **Decision Boundary:**
   - The decision boundary of KNN is flexible and adapts to the distribution of instances in the feature space.

4. **Hyperparameter:**
   - The choice of \(k\) is a hyperparameter that can impact the model's performance. A smaller \(k\) may result in a more sensitive model, while a larger \(k\) may lead to smoother decision boundaries.

### Use Cases:

- **Image Recognition:**
  - Identifying the category of an image based on its features.

- **Recommendation Systems:**
  - Recommending items to users based on the preferences of similar users.

- **Anomaly Detection:**
  - Detecting unusual patterns or outliers in data.

- **Medical Diagnosis:**
  - Predicting the likelihood of a disease based on patient characteristics.

### Challenges and Considerations:

- **Sensitivity to Noise and Outliers:**
  - KNN can be sensitive to noisy or irrelevant features and outliers.

- **Computational Complexity:**
  - Making predictions can be computationally expensive, especially for large datasets.

- **Scaling:**
  - Feature scaling is important, as features with larger scales may dominate the distance calculations.

### Variants:

- **Weighted KNN:**
  - Assigns different weights to neighbors based on their distance.

- **KD-Tree and Ball-Tree:**
  - Data structures used to speed up the search for nearest neighbors.

- **Distance Metrics:**
  - Different distance metrics may be used based on the nature of the data.

KNN is a simple and intuitive algorithm that works well for various tasks. Its flexibility and ease of implementation make it a valuable tool, especially when the data is not well-behaved or when interpretability is important. However, it may not perform optimally in high-dimensional or large-scale datasets.